-- Giá thị trường được lấy theo cơ chế APP-TRIGGERED, không dùng cron chạy nền:
--   • App (PriceRefreshService) gọi Edge Function fetch-gold-price / fetch-stock-price
--     mỗi khi mở app / resume, có throttle 2 phút.
--   • Edge Function dùng filterChangedSnapshots (_shared/dedupe.ts) — chỉ ghi vào
--     price_snapshots khi giá đổi, nên không phát sinh dòng trùng.
-- => Server nhẹ (không chạy nền), app vẫn có giá mới mỗi lần mở.
--
-- Bản đầu của migration này từng lên lịch pg_cron gọi 2 function; đã gỡ lịch
-- (cron.unschedule) khi chuyển sang app-triggered. File giữ nguyên số hiệu 0007
-- để lịch sử migration không lệch; cố ý không tạo cron job nào.
--
-- Nếu sau này muốn có nền dự phòng (vd chạy vài lần/ngày cho widget khi không mở
-- app), bật lại pg_cron + pg_net và cron.schedule ở một migration mới.
